redmine-5.0.11/config/routes.rb
# frozen_string_literal: true

# Redmine - project management software
# Copyright (C) 2006-  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

Rails.application.routes.draw do
  root :to => 'welcome#index', :as => 'home'

  match 'login', :to => 'account#login', :as => 'signin', :via => [:get, :post]
  match 'logout', :to => 'account#logout', :as => 'signout', :via => [:get, :post]
  match 'account/twofa/confirm', :to => 'account#twofa_confirm', :via => :get
  match 'account/twofa/resend', :to => 'account#twofa_resend', :via => :post
  match 'account/twofa', :to => 'account#twofa', :via => [:get, :post]
  match 'account/register', :to => 'account#register', :via => [:get, :post], :as => 'register'
  match 'account/lost_password', :to => 'account#lost_password', :via => [:get, :post], :as => 'lost_password'
  match 'account/activate', :to => 'account#activate', :via => :get
  get 'account/activation_email', :to => 'account#activation_email', :as => 'activation_email'

  match '/news/preview', :controller => 'previews', :action => 'news', :as => 'preview_news', :via => [:get, :post, :put, :patch]
  match '/issues/preview', :to => 'previews#issue', :as => 'preview_issue', :via => [:get, :post, :put, :patch]
  match '/preview/text', :to => 'previews#text', :as => 'preview_text', :via => [:get, :post, :put, :patch]

  match 'projects/:id/wiki/destroy', :to => 'wikis#destroy', :via => [:get, :post]

  match 'boards/:board_id/topics/new', :to => 'messages#new', :via => [:get, :post], :as => 'new_board_message'
  get 'boards/:board_id/topics/:id', :to => 'messages#show', :as => 'board_message'
  match 'boards/:board_id/topics/quote/:id', :to => 'messages#quote', :via => [:get, :post]
  get 'boards/:board_id/topics/:id/edit', :to => 'messages#edit'

  post 'boards/:board_id/topics/preview', :to => 'messages#preview', :as => 'preview_board_message'
  post 'boards/:board_id/topics/:id/replies', :to => 'messages#reply'
  post 'boards/:board_id/topics/:id/edit', :to => 'messages#edit'
  post 'boards/:board_id/topics/:id/destroy', :to => 'messages#destroy'

  # Auto complete routes
  match '/issues/auto_complete', :to => 'auto_completes#issues', :via => :get, :as => 'auto_complete_issues'
  match '/wiki_pages/auto_complete', :to => 'auto_completes#wiki_pages', :via => :get, :as => 'auto_complete_wiki_pages'

  # Misc issue routes. TODO: move into resources
  match '/issues/context_menu', :to => 'context_menus#issues', :as => 'issues_context_menu', :via => [:get, :post]
  match '/issues/changes', :to => 'journals#index', :as => 'issue_changes', :via => :get
  match '/issues/:id/quoted', :to => 'journals#new', :id => /\d+/, :via => :post, :as => 'quoted_issue'

  resources :journals, :only => [:edit, :update] do
    member do
      get 'diff'
    end
  end

  get '/projects/:project_id/issues/gantt', :to => 'gantts#show', :as => 'project_gantt'
  get '/issues/gantt', :to => 'gantts#show'

  get '/projects/:project_id/issues/calendar', :to => 'calendars#show', :as => 'project_calendar'
  get '/issues/calendar', :to => 'calendars#show'

  get 'projects/:id/issues/report', :to => 'reports#issue_report', :as => 'project_issues_report'
  get 'projects/:id/issues/report/:detail', :to => 'reports#issue_report_details', :as => 'project_issues_report_details'

  get   '/issues/imports/new', :to => 'imports#new',
        :defaults => {:type => 'IssueImport'}, :as => 'new_issues_import'
  get   '/time_entries/imports/new', :to => 'imports#new',
        :defaults => {:type => 'TimeEntryImport'}, :as => 'new_time_entries_import'
  get   '/users/imports/new', :to => 'imports#new',
        :defaults => {:type => 'UserImport'}, :as => 'new_users_import'
  post  '/imports', :to => 'imports#create', :as => 'imports'
  get   '/imports/:id', :to => 'imports#show', :as => 'import'
  match '/imports/:id/settings', :to => 'imports#settings', :via => [:get, :post], :as => 'import_settings'
  match '/imports/:id/mapping', :to => 'imports#mapping', :via => [:get, :post], :as => 'import_mapping'
  match '/imports/:id/run', :to => 'imports#run', :via => [:get, :post], :as => 'import_run'

  match 'my/account', :controller => 'my', :action => 'account', :via => [:get, :put]
  match 'my/account/destroy', :controller => 'my', :action => 'destroy', :via => [:get, :post], :as => :delete_my_account
  match 'my/page', :controller => 'my', :action => 'page', :via => :get
  post 'my/page', :to => 'my#update_page'
  match 'my', :controller => 'my', :action => 'index', :via => :get # Redirects to my/page
  get 'my/api_key', :to => 'my#show_api_key', :as => 'my_api_key'
  post 'my/api_key', :to => 'my#reset_api_key'
  post 'my/atom_key', :to => 'my#reset_atom_key', :as => 'my_atom_key'
  match 'my/password', :controller => 'my', :action => 'password', :via => [:get, :post]
  match 'my/add_block', :controller => 'my', :action => 'add_block', :via => :post
  match 'my/remove_block', :controller => 'my', :action => 'remove_block', :via => :post
  match 'my/order_blocks', :controller => 'my', :action => 'order_blocks', :via => :post
  match 'my/twofa/activate/init', :controller => 'twofa', :action => 'activate_init', :via => :post
  match 'my/twofa/:scheme/activate/init', :controller => 'twofa', :action => 'activate_init', :via => :post
  match 'my/twofa/:scheme/activate/confirm', :controller => 'twofa', :action => 'activate_confirm', :via => :get
  match 'my/twofa/:scheme/activate', :controller => 'twofa', :action => 'activate', :via => [:get, :post]
  match 'my/twofa/:scheme/deactivate/init', :controller => 'twofa', :action => 'deactivate_init', :via => :post
  match 'my/twofa/:scheme/deactivate/confirm', :controller => 'twofa', :action => 'deactivate_confirm', :via => :get
  match 'my/twofa/:scheme/deactivate', :controller => 'twofa', :action => 'deactivate', :via => [:get, :post]
  match 'my/twofa/select_scheme', :controller => 'twofa', :action => 'select_scheme', :via => :get
  match 'my/twofa/backup_codes/init', :controller => 'twofa_backup_codes', :action => 'init', :via => :post
  match 'my/twofa/backup_codes/confirm', :controller => 'twofa_backup_codes', :action => 'confirm', :via => :get
  match 'my/twofa/backup_codes/create', :controller => 'twofa_backup_codes', :action => 'create', :via => [:get, :post]
  match 'my/twofa/backup_codes', :controller => 'twofa_backup_codes', :action => 'show', :via => [:get]
  match 'users/:user_id/twofa/deactivate', :controller => 'twofa', :action => 'admin_deactivate', :via => :post

  resources :users do
    resources :memberships, :controller => 'principal_memberships'
    resources :email_addresses, :only => [:index, :create, :update, :destroy]
  end

  post 'watchers/watch', :to => 'watchers#watch', :as => 'watch'
  delete 'watchers/watch', :to => 'watchers#unwatch'
  get 'watchers/new', :to => 'watchers#new', :as => 'new_watchers'
  post 'watchers', :to => 'watchers#create'
  post 'watchers/append', :to => 'watchers#append'
  delete 'watchers', :to => 'watchers#destroy'
  get 'watchers/autocomplete_for_mention', to: 'watchers#autocomplete_for_mention', via: [:get]
  get 'watchers/autocomplete_for_user', :to => 'watchers#autocomplete_for_user'
  # Specific routes for issue watchers API
  post 'issues/:object_id/watchers', :to => 'watchers#create', :object_type => 'issue'
  delete 'issues/:object_id/watchers/:user_id' => 'watchers#destroy', :object_type => 'issue'

  resources :projects do
    collection do
      get 'autocomplete'
    end

    member do
      get 'settings(/:tab)', :action => 'settings', :as => 'settings'
      match 'archive', :via => [:post, :put]
      match 'unarchive', :via => [:post, :put]
      match 'close', :via => [:post, :put]
      match 'reopen', :via => [:post, :put]
      match 'copy', :via => [:get, :post]
      match 'bookmark', :via => [:delete, :post]
    end

    shallow do
      resources :memberships, :controller => 'members' do
        collection do
          get 'autocomplete'
        end
      end
    end

    resource :enumerations, :controller => 'project_enumerations', :only => [:update, :destroy]

    get 'issues/:copy_from/copy', :to => 'issues#new', :as => 'copy_issue'
    resources :issues, :only => [:index, :new, :create]
    # Used when updating the form of a new issue
    post 'issues/new', :to => 'issues#new'

    resources :files, :only => [:index, :new, :create]

    resources :versions, :except => [:index, :show, :edit, :update, :destroy] do
      collection do
        put 'close_completed'
      end
    end
    get 'versions.:format', :to => 'versions#index'
    get 'roadmap', :to => 'versions#index', :format => false
    get 'versions', :to => 'versions#index'

    resources :news, :except => [:show, :edit, :update, :destroy]
    resources :time_entries, :controller => 'timelog', :except => [:show, :edit, :update, :destroy] do
      get 'report', :on => :collection
    end
    resources :queries, :only => [:new, :create]
    shallow do
      resources :issue_categories
    end
    resources :documents, :except => [:show, :edit, :update, :destroy]
    resources :boards
    shallow do
      resources :repositories, :except => [:index, :show] do
        member do
          match 'committers', :via => [:get, :post]
        end
      end
    end

redmine-5.0.11/app/views/issues/tabs/_changesets.html.erb
<% @changesets.each do |changeset| %>
  <div id="changeset-<%= changeset.id %>" class="changeset journal">
    <div class="note">
    <h4 class='note-header'>
      <%= avatar(changeset.user, :size => "24") %>
      <%= authoring changeset.committed_on, changeset.author, :label => :label_added_time_by %>
    </h4>
    <p>
    <%= "#{changeset.project.name} - " unless changeset.project == project %>
    <%= link_to_revision(changeset, changeset.repository,
                        :text => "#{l(:label_revision)} #{changeset.format_identifier}") %>
    <% if changeset.filechanges.any? && User.current.allowed_to?(:browse_repository, changeset.project) %>
    (<%= link_to(l(:label_diff),
           :controller => 'repositories',
           :action => 'diff',
           :id     => changeset.project,
           :repository_id => changeset.repository.identifier_param,
           :path   => "",
           :rev    => changeset.identifier) %>)
    <% end %></p>

    <div class="wiki changeset-comments">
      <%= format_changeset_comments changeset %>
    </div>
    </div>
  </div>
  <%= call_hook(:view_issues_history_changeset_bottom, { :changeset => changeset }) %>
<% end %>

redmine-5.0.11/app/views/issues/tabs/_history.html.erb
<%
  issue = tab[:locals][:issue]
  journals = tab[:locals][:journals]
%>

<% reply_links = issue.notes_addable? -%>
<% for journal in journals %>
  <div id="change-<%= journal.id %>" class="<%= journal.css_classes %>">
    <div id="note-<%= journal.indice %>" class="note">
    <div class="contextual">
      <span class="journal-actions"><%= render_journal_actions(issue, journal, :reply_links => reply_links) %></span>
      <a href="#note-<%= journal.indice %>" class="journal-link">#<%= journal.indice %></a>
    </div>
    <h4 class='note-header'>
      <%= avatar(journal.user) %>
      <%= authoring journal.created_on, journal.user, :label => :label_updated_time_by %>
      <%= render_private_notes_indicator(journal) %>
    </h4>

    <% if journal.details.any? %>
    <ul class="details">
      <% details_to_strings(journal.visible_details).each do |string| %>
       <li><%= string %></li>
      <% end %>
    </ul>
    <% if Setting.thumbnails_enabled? && (thumbnail_attachments = journal_thumbnail_attachments(journal)).any? %>
      <div class="thumbnails">
        <% thumbnail_attachments.each do |attachment| %>
          <div><%= thumbnail_tag(attachment) %></div>
        <% end %>
      </div>
    <% end %>
    <% end %>
    <%= render_notes(issue, journal, :reply_links => reply_links) unless journal.notes.blank? %>
    </div>
  </div>
  <%= call_hook(:view_issues_history_journal_bottom, { :journal => journal }) %>
<% end %>

<% heads_for_wiki_formatter if User.current.allowed_to?(:edit_issue_notes, issue.project) || User.current.allowed_to?(:edit_own_issue_notes, issue.project) %>

redmine-5.0.11/app/views/issues/tabs/_time_entries.html.erb
<% for time_entry in time_entries%>
  <div id="time-entry-<%= time_entry.id %>" class="time_entry journal">
    <div class="note">
    <% if time_entry.editable_by?(User.current) -%>
      <div class="contextual">
        <span class="journal-actions">
        <%= link_to l(:button_edit), edit_time_entry_path(time_entry),
                    :title => l(:button_edit),
                    :class => 'icon-only icon-edit' %>
        <%= link_to l(:button_delete), time_entry_path(time_entry),
                    :data => {:confirm => l(:text_are_you_sure)},
                    :method => :delete,
                    :title => l(:button_delete),
                    :class => 'icon-only icon-del' %>
        </span>
      </div>
    <% end -%>
    <h4 class='note-header'>
      <%= avatar(time_entry.user, :size => "24") %>
      <%= authoring time_entry.created_on, time_entry.user, :label => :label_added_time_by %>
    </h4>
    <ul class="details">
      <li>
        <strong><%= l(:label_time_entry_plural) %></strong>:
        <%= l_hours_short time_entry.hours %>
      </li>
    </ul>
    <p><%= time_entry.comments %></p>
    </div>
  </div>
  <%= call_hook(:view_issues_history_time_entry_bottom, { :time_entry => time_entry }) %>
<% end %>